### ISSUE TITLE
Rebuild dolly but got an error message below (my system: ubuntu 18 LTS, ros2 Dashing)

### ISSUE THREAD

**Issue by phunghoabk** [chapulina/dolly#11]
When I moved the girl, the Lidar visulazation was showing the changes of Lidar rays, but the robot did move or follow. And the Ubuntu command interface showed the error

[gzclient   -2] Node::Advertise(): Error advertising a topic. Did you forget to start the discovery service?

Thank you for your help

**Comment by chapulina** [comment]
Hi @phunghoabk , I just tested a fresh Dashing workspace and it worked for me.

Some things you can try to debug:

1. See if you have all the necessary topics:

```
$ ros2 topic list | grep dolly
/dolly/cmd_vel
/dolly/laser_scan
/dolly/odom
/dolly/parameter_events
/dolly/rosout
```

2. See if you're getting laser scans:

`ros2 topic echo /dolly/laser_scan`

3. See if you're getting commands:

`ros2 topic echo /dolly/cmd_vel`

**Comment by chapulina** [comment]
@phunghoabk , I'm going to close this issue, but feel free to reopen if the problem comes back and you have more information on how to reproduce it.
