### ISSUE TITLE
ROS2 Foxy | Package 'dolly_ignition' not found

### ISSUE THREAD

**Issue by ruffsl** [chapulina/dolly#25]
I'm not sure what may have gone wrong in packaging `dolly_ignition` for foxy release, but the binary apt release doesn't seem to install its own package directory in the ros2 distro share folder:

```
$ sudo apt install ros-foxy-dolly-ignition 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-foxy-dolly-ignition is already the newest version (0.3.0-1focal.20200911.235014).
The following packages were automatically installed and are no longer required:
  apturl apturl-common libatomic1:i386 libbsd0:i386 libcue2 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi7:i386
  libfprint-2-tod1 libgl1:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libgsf-1-114 libgsf-1-common libllvm10:i386 libllvm9 libllvm9:i386 libnvidia-common-440
  libpciaccess0:i386 libplayerctl2 libsensors5:i386 libstdc++6:i386 libtracker-control-2.0-0 libtracker-miner-2.0-0 libvulkan1:i386 libwayland-client0:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386
  libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-randr0:i386 libxcb-sync1:i386 libxcb1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxshmfence1:i386
  libxxf86vm1:i386 mesa-vulkan-drivers:i386 tracker tracker-extract tracker-miner-fs
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

$ apt list ros-foxy-ros-ign
Listing... Done
ros-foxy-ros-ign/focal,now 0.221.1-1focal.20200911.235346 amd64 [installed]

$ source /opt/ros/foxy/setup.bash 

$ ros2 launch dolly_ignition dolly.launch.py
Package 'dolly_ignition' not found: "package 'dolly_ignition' not found, searching: ['/opt/ros/foxy']"

$ ls /opt/ros/foxy/share/ | grep dolly
dolly
dolly_follow
```

I'm guessing from how the cmake is written, if the build farm was missing the necessary build dependency from ignition, then no build artifacts would have been generated/packaged, given such build dependencies are not explicitly declared in a package manifest. See https://github.com/chapulina/dolly/pull/22#discussion_r491258197 and bellow:

https://github.com/chapulina/dolly/blob/349c35288b3a78a66249a1eef66bd507a0fed750/dolly_ignition/CMakeLists.txt#L7-L10

**Comment by chapulina** [comment]
> such build dependencies are not explicitly declared in a package manifest

`ros_ign_bridge` and `ros_ign_gazebo` are declared as exec dependencies. I realize now that they should be build dependencies to satisfy the cmake configuration step

https://github.com/chapulina/dolly/blob/349c35288b3a78a66249a1eef66bd507a0fed750/dolly_ignition/package.xml#L15-L16
