### ISSUE TITLE
The station environment doesn't load properly in Ignition Gazebo

### ISSUE THREAD

**Issue by Reka-Berci-Hajnovics** [chapulina/dolly#29]
After following the instructions to install dolly from source, I've tried to launch it in ignition: ` ros2 launch dolly_ignition dolly.launch.py`
After launching it, the environment is broken and I get many warnings.

![dolly_error](https://user-images.githubusercontent.com/24480017/93335187-59f69780-f826-11ea-985a-c39083d9aab3.png)

**Comment by Reka-Berci-Hajnovics** [comment]
After updating my Nvidia drivers it looks better, but the actor and the station environment don't load.
![Screenshot from 2020-10-05 12-03-49](https://user-images.githubusercontent.com/24480017/95066711-0d0a3080-0703-11eb-82a5-fcaf19ad7b91.png)

**Comment by chapulina** [comment]
Running `sudo apt update && sudo apt upgrade` should get you rid of some warnings.

**Comment by Reka-Berci-Hajnovics** [comment]
After running the update and upgrade it looks like the following:
![Screenshot from 2020-10-06 10-18-21](https://user-images.githubusercontent.com/24480017/95176602-5dde5f80-07bd-11eb-81c9-ffbb7a3ae48d.png)

**Comment by Reka-Berci-Hajnovics** [comment]
Hi,

The solution used in [ignitionrobotics/ign-gazebo#350](https://github.com/ignitionrobotics/ign-gazebo/issues/350) thread solved also this problem. As described [here,](https://github.com/osrf/subt/issues/438#issuecomment-640290247) it is caused by the usage of different decimal separator, the comma is used in Europe and the period in the USA. 

I have run the launch file with English locale:
```
LC_ALL=C LANG=C ros2 launch dolly_ignition dolly.launch.py
```
![dolly](https://user-images.githubusercontent.com/24480017/96001358-37ad6500-0e38-11eb-94a3-7fc23ed8c6c6.png)

**Comment by chapulina** [comment]
Thank you for closing the loop, @Reka-Berci-Hajnovics . I'll close this issue but leave the one on `ign-gazebo` open until that we find a way to fix this internally so that users don't need to manually set the locale.
