### ISSUE TITLE
Failed to initialize init_options when running dolly.launch.py

### ISSUE THREAD

**Issue by RodBelaFarin** [chapulina/dolly#3]
Following the instructions from the tutorial, I end up in the following error:

`ros2 launch dolly_gazebo dolly.launch.py world:=dolly_city.world
`

[ERROR] [launch.LaunchService]: Caught exception in launch (see debug for traceback
): Failed to initialize init_options: failed to load shared library of rmw implemen
tation. Exception: Cannot load library: /opt/ros/crystal/lib/librmw_fastrtps_cpp.so
: undefined symbol: _ZTVN8eprosima8fastrtps27DataRepresentationQosPolicyE, at /tmp/binarydeb/ros-crystal-rmw-implementation-0.6.1/src/functions.cpp:136, at /tmp/binarydeb/ros-crystal-rcl-0.6.5/src/rcl/init_options.c:55

**Comment by chapulina** [comment]
There seems to be a problem with your ROS 2 crystal installation. How did you install it?

**Comment by RodBelaFarin** [comment]
I followed the instructions for Debian installation using Ubuntu 18.04
https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Install-Debians/
