### ISSUE TITLE
Github Actions Ogre2 error accessing DISPLAY

### ISSUE THREAD

**Issue by j-rivero** [chapulina/dolly#44]
While working on check the headless mode inside GitHub Actions and reading #41 I just found that there is a problem reported in [the log](https://github.com/chapulina/dolly/runs/4037744305?check_suite_focus=true):

```
1: [follow_ignition_TEST-1] [Dbg] [SimulationRunner.cc:527] Creating postupdate worker thread (1)
1: [follow_ignition_TEST-1] [Msg] DiffDrive subscribing to twist messages on [/dolly/cmd_vel]
1: [follow_ignition_TEST-1] [Err] [Ogre2RenderEngine.cc:376] Unable to open display: :1.0
1: [parameter_bridge-3] [INFO] [1635442786.958195465] [ros_ign_bridge]: Passing message from ROS geometry_msgs/msg/Twist to Ignition ignition.msgs.Twist (showing msg only once per type)
1: [follow_ignition_TEST-1] [Wrn] [follow_ignition_TEST.cpp:193] Recorded [5000] poses
```

The test ended with a success, not sure if it is affecting anything seriously.

**Comment by chapulina** [comment]
Yeah it looks like that doesn't affect the test results. If rendering wasn't working, the test should fail because the GPU lidar wouldn't be publishing values.
