### ISSUE TITLE
Dolly is not moving/following

### ISSUE THREAD

**Issue by yahoo2016** [chapulina/dolly#7]
Could load world, Dolly and other models, but Dolly is not moving/following, there is no blue laser beam.

**Comment by chapulina** [comment]
Could you try running in verbose mode and see if any error messages are printed? (i.e. add `verbose:=true` to the launch command)

**Comment by yahoo2016** [comment]
Screen capture is attached.  I noticed warning in reviz "no tf data".
![Screenshot from 2019-10-14 20-53-35](https://user-images.githubusercontent.com/16500469/66792129-601d1f00-eec5-11e9-8711-5be51b92149f.png)

**Comment by chapulina** [comment]
Thanks for the screenshot. I can't see what would be wrong, it looks like all nodes were properly loaded for the robot.

1. Can you confirm that the simulation is not paused (i.e. sim time is increasing)?

1. What do you get with `ros2 node list`?

1. How did you install ROS 2? What version are you using? Which branch of this repository are you using?

**Comment by yahoo2016** [comment]
Thanks for the troubleshooting hints.
1. Simulation was running I got FPS < 10. 
2. "ros2 node list" shows
/launch_ros
/gazebo
/dolly/laser
/dolly/diff_drive
/follow
/rviz
3. I used a script to install dashing:
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt update && sudo apt install curl gnupg2 lsb-release
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
export CHOOSE_ROS_DISTRO=dashing  
sudo apt update
sudo apt install ros-$CHOOSE_ROS_DISTRO-desktop -y
sudo apt install python3-argcomplete -y
sudo apt install ros-$CHOOSE_ROS_DISTRO-ros1-bridge -y
sudo apt install python3-colcon-common-extensions -y

Based on the warning "Conversion of sensor type[gpu_ray] not supported", I searched/identified Nvidia graphic card and installed driver by:
ubuntu-drivers devices 
sudo ubuntu-drivers autoinstall

after reboot, the demo worked great:
![Screenshot from 2019-10-15 08-36-50](https://user-images.githubusercontent.com/16500469/66832071-19601100-ef27-11e9-9ac3-637d2f0ed032.png)

**Comment by chapulina** [comment]
Glad to hear it worked ok! I'll close this issue for now, but feel free to reopen if the problem comes back. :v:
